services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    networks:
      - "crypto-wallet-net"
    depends_on:
      - backend
      - db

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    env_file: "./backend/.env"
    networks:
      - "crypto-wallet-net"
    depends_on:
      - db

  db:
    image: mongo:6-jammy
    volumes:
      - db_data:/data/db
    networks:
      - "crypto-wallet-net"

volumes:
  db_data:

networks:
  crypto-wallet-net:
